// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLvGcmFhfiTJoCLhIF7r3KzBhWJxl55jU',
    appId: '1:825578601931:web:cfda9ce08e23ec4405ca4e',
    messagingSenderId: '825578601931',
    projectId: 'chatapp-94660',
    authDomain: 'chatapp-94660.firebaseapp.com',
    databaseURL: 'https://chatapp-94660-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-94660.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwMdK0vMOm3Cn20vmNfFrmbmqncERCvaM',
    appId: '1:825578601931:android:ba7ae3e7963d4e2a05ca4e',
    messagingSenderId: '825578601931',
    projectId: 'chatapp-94660',
    databaseURL: 'https://chatapp-94660-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-94660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqz1oexwEt3k3HFA3-9z9g41jHR4VZtdc',
    appId: '1:825578601931:ios:f440c2e4797b910e05ca4e',
    messagingSenderId: '825578601931',
    projectId: 'chatapp-94660',
    databaseURL: 'https://chatapp-94660-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-94660.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
